# @package __global__

datasource:
  train: egs/fMRI_downstream/ds002105/train
  valid: egs/fMRI_downstream/ds002105/valid
  evaluate: egs/fMRI_downstream/ds002105/test
  generate: egs/fMRI_downstream/ds002105/test
