# @package __global__

defaults:
  - encodec_fMRI/default

seanet:
  dimension: 128
  n_filters: 1024
  n_residual_layers: 1
  ratios: [1,0.5,0.5]
  time_extension_ratios: [1,1,3]
  add_noise: false

rvq:
  n_q: 8
  q_dropout: false
  bins: 1024
  use_gaussian_layer: null
